/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PayRouteImport } from './routes/pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIdRouteImport } from './routes/games.$id'
import { Route as AdminKhqrDebugRouteImport } from './routes/admin.khqr-debug'
import { Route as ApiPaymentCreateRouteImport } from './routes/api/payment/create'
import { Route as ApiPublicHooksVerifyBakongTopupsRouteImport } from './routes/api/public/hooks/verify-bakong-topups'
import { Route as ApiPublicHooksExpireBakongTopupsRouteImport } from './routes/api/public/hooks/expire-bakong-topups'
import { Route as ApiPaymentStatusIdRouteImport } from './routes/api/payment/status.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKhqrDebugRoute = AdminKhqrDebugRouteImport.update({
  id: '/khqr-debug',
  path: '/khqr-debug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment/create',
  path: '/api/payment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksVerifyBakongTopupsRoute =
  ApiPublicHooksVerifyBakongTopupsRouteImport.update({
    id: '/api/public/hooks/verify-bakong-topups',
    path: '/api/public/hooks/verify-bakong-topups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireBakongTopupsRoute =
  ApiPublicHooksExpireBakongTopupsRouteImport.update({
    id: '/api/public/hooks/expire-bakong-topups',
    path: '/api/public/hooks/expire-bakong-topups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentStatusIdRoute = ApiPaymentStatusIdRouteImport.update({
  id: '/api/payment/status/$id',
  path: '/api/payment/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/khqr-debug': typeof AdminKhqrDebugRoute
  '/games/$id': typeof GamesIdRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/status/$id': typeof ApiPaymentStatusIdRoute
  '/api/public/hooks/expire-bakong-topups': typeof ApiPublicHooksExpireBakongTopupsRoute
  '/api/public/hooks/verify-bakong-topups': typeof ApiPublicHooksVerifyBakongTopupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/khqr-debug': typeof AdminKhqrDebugRoute
  '/games/$id': typeof GamesIdRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/status/$id': typeof ApiPaymentStatusIdRoute
  '/api/public/hooks/expire-bakong-topups': typeof ApiPublicHooksExpireBakongTopupsRoute
  '/api/public/hooks/verify-bakong-topups': typeof ApiPublicHooksVerifyBakongTopupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/khqr-debug': typeof AdminKhqrDebugRoute
  '/games/$id': typeof GamesIdRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/status/$id': typeof ApiPaymentStatusIdRoute
  '/api/public/hooks/expire-bakong-topups': typeof ApiPublicHooksExpireBakongTopupsRoute
  '/api/public/hooks/verify-bakong-topups': typeof ApiPublicHooksVerifyBakongTopupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/pay'
    | '/register'
    | '/sitemap.xml'
    | '/admin/khqr-debug'
    | '/games/$id'
    | '/api/payment/create'
    | '/api/payment/status/$id'
    | '/api/public/hooks/expire-bakong-topups'
    | '/api/public/hooks/verify-bakong-topups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/pay'
    | '/register'
    | '/sitemap.xml'
    | '/admin/khqr-debug'
    | '/games/$id'
    | '/api/payment/create'
    | '/api/payment/status/$id'
    | '/api/public/hooks/expire-bakong-topups'
    | '/api/public/hooks/verify-bakong-topups'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/library'
    | '/login'
    | '/pay'
    | '/register'
    | '/sitemap.xml'
    | '/admin/khqr-debug'
    | '/games/$id'
    | '/api/payment/create'
    | '/api/payment/status/$id'
    | '/api/public/hooks/expire-bakong-topups'
    | '/api/public/hooks/verify-bakong-topups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GamesIdRoute: typeof GamesIdRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  ApiPaymentStatusIdRoute: typeof ApiPaymentStatusIdRoute
  ApiPublicHooksExpireBakongTopupsRoute: typeof ApiPublicHooksExpireBakongTopupsRoute
  ApiPublicHooksVerifyBakongTopupsRoute: typeof ApiPublicHooksVerifyBakongTopupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/khqr-debug': {
      id: '/admin/khqr-debug'
      path: '/khqr-debug'
      fullPath: '/admin/khqr-debug'
      preLoaderRoute: typeof AdminKhqrDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/payment/create': {
      id: '/api/payment/create'
      path: '/api/payment/create'
      fullPath: '/api/payment/create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-bakong-topups': {
      id: '/api/public/hooks/verify-bakong-topups'
      path: '/api/public/hooks/verify-bakong-topups'
      fullPath: '/api/public/hooks/verify-bakong-topups'
      preLoaderRoute: typeof ApiPublicHooksVerifyBakongTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-bakong-topups': {
      id: '/api/public/hooks/expire-bakong-topups'
      path: '/api/public/hooks/expire-bakong-topups'
      fullPath: '/api/public/hooks/expire-bakong-topups'
      preLoaderRoute: typeof ApiPublicHooksExpireBakongTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/status/$id': {
      id: '/api/payment/status/$id'
      path: '/api/payment/status/$id'
      fullPath: '/api/payment/status/$id'
      preLoaderRoute: typeof ApiPaymentStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminKhqrDebugRoute: typeof AdminKhqrDebugRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKhqrDebugRoute: AdminKhqrDebugRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GamesIdRoute: GamesIdRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  ApiPaymentStatusIdRoute: ApiPaymentStatusIdRoute,
  ApiPublicHooksExpireBakongTopupsRoute: ApiPublicHooksExpireBakongTopupsRoute,
  ApiPublicHooksVerifyBakongTopupsRoute: ApiPublicHooksVerifyBakongTopupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
